### ISSUE TITLE
default minification settings are dangerous 

### ISSUE THREAD

**Issue by mkoryak** [webpack-contrib/html-loader#35] opened 2015-10-28 14:02 UTC
By default, this plugin will blow away 'redundant' attributes. This means that it will remove `type='text'` from an input. This is bad because it breaks styles, and potentially javascript etc. 

The html minifier you use has settings that it calls "safe", you should default to those at most.

**Comment by thelinuxlich** [comment] 2015-11-03 19:21
+1 this is ridiculous

**Comment by mkoryak** [comment] 2015-11-04 01:22
it would be less horrible if it was documented. would you like a PR for that?

**Comment by chrisnicola** [comment] 2015-11-28 00:13
Ran into this as well, adding `?removeRedundantAttributes=false` to the query fixes it. It probably should be set this way by default though and the minification options of the HTML minifier should be documented somewhere. Took me a while to track the cause of this down.

**Comment by jantimon** [comment] 2015-12-17 09:16
Got the same problem with `removeOptionalTags`: #40

**Comment by chrisnicola** [comment] 2015-12-17 19:05
@jantimon what does removeOptionalTags break?

**Comment by mkoryak** [comment] 2015-12-17 20:13
@chrisnicola 
it will break this css

```css
[type="text"] {
   background-color: red;
}
```
or this js

```js
$('[type="text"]').on('click', function(){ alert('poop'); });
```

Also any other code that relies on anything this thing will remove. 

you get the idea.

**Comment by chrisnicola** [comment] 2015-12-18 04:44
Optional tags just removes closing </html> </body> and a few other tags. I think you are talking about removeDefaultAttributes

**Closed** 2018-02-06 04:08 UTC
Labels: scope: Minifier, type: Bug

**Comment by mkoryak** [comment] 2018-02-06 07:17
Nice, it looks fixed. 

FYI, you don't need to use `typeof` to compare something to undefined. It was a thing people did when one could reassign `undefined`. You can just do `if (thing === undefined)` and it works great.  

Same for most other comparisons. Some of them use typeof because of iframe issues etc. You dont have those here.
