### ISSUE TITLE
Error when decoding special characters in decodeURIComponent in source-plugin.js

### ISSUE THREAD

**Issue by yangdan8** [webpack-contrib/html-loader#319] opened 2020-09-01 12:02 UTC
Latest code:
/dist/plugins/source-plugin.js: line 586
const importKey = (0, _loaderUtils.urlToRequest)(decodeURIComponent(source.value), root);

Error:
URIError: URI malformed

decodeURIComponent

source-plugin.js:586 process
[html-loader]/dist/plugins/source-plugin.js:586:5 4

utils.js:26 Object.process
[html-loader]/dist/utils.js:26:19

URIError: URI malformed

compiler.js:80
[html-webpack-plugin]/lib/compiler.js:80:16

Compiler.js:343
[webpack]/lib/Compiler.js:343:11

Compiler.js:681
[webpack]/lib/Compiler.js:681:15

Debug and get:
The value of source.value is ./<%- htmlWebpackPlugin.options.assetsFileName %>.umd.js

decodeURIComponent error when decoding special characters

**Comment by evilebottnawi** [comment] 2020-09-01 12:12
Because it is invalid url and can't be resolved, please create reproducible test repo

**Comment by yangdan8** [comment] 2020-09-17 06:27
![image](https://user-images.githubusercontent.com/16515026/93428323-d0ac9700-f8f1-11ea-970e-fc3d97f702d7.png)

**Comment by yangdan8** [comment] 2020-09-17 06:27
decodeURIComponent('./<%- htmlWebpackPlugin.options.assetsFileName %>.umd.js')

**Comment by evilebottnawi** [comment] 2020-09-17 10:47
Because you have non valid URL, please use `urlFilter` to avoid resolving them

**Closed by evilebottnawi** 2020-09-17 10:47 UTC

**Comment by yangdan8** [comment] 2020-09-18 04:06
The error comes from @vue/cli-service/node_modules/html-webpack-plugin calling this function

**Comment by evilebottnawi** [comment] 2020-09-18 11:17
So please create this issue in `html-webpack-plugin`
